### ISSUE TITLE
Can this repo be removed?

### ISSUE THREAD

**Issue by hlgr360** [Haufe-Lexware/hl.pas.samlplugin#3]
There appears to be no more activity on this repo. I would like to cleanup according to our Open Source policy.

**Comment by eprigorodov** [comment]
It seems to be the only existing PAS plugin that can integrate a Zope instance with AD FS (dm.zope.saml2 only works in a Plone site). It has weight 9 on PyPI.

**Comment by hlgr360** [comment]
Is anyone taking care of it and feeling responsible?
______________________________________________________
Holger Reinhardt
CTO – Haufe.Group
+49-170-9165551 | @hlgr360 | http://work.haufegroup.io

Haufe-Lexware GmbH & Co.KG
Munzinger Str. 9, 79111 Freiburg
http://www.haufe-lexware.com<http://www.haufe-lexware.com/>

On Jul 6, 2017, at 12:01 PM, Evgeny Prigorodov <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems to be the only existing PAS plugin that can integrate a Zope instance with AD FS (dm.zope.saml2 only works in a Plone site). It has weight 9 on PyPI.

**Comment by saromba** [comment]
Hi Holger,

 

we (the LexBIZ Team) are responsible for that repo.

What is the current task ? Evgeny only commented something...

 

Regards,

Sascha Rombach
 

 

Gesendet: Freitag, 07. Juli 2017 um 11:05 Uhr
Von: "Holger Reinhardt" <notifications@github.com>
An: "Haufe-Lexware/hl.pas.samlplugin" <hl.pas.samlplugin@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Haufe-Lexware/hl.pas.samlplugin] Can this repo be removed? (#3)

Is anyone taking care of it and feeling responsible?
______________________________________________________
Holger Reinhardt
CTO – Haufe.Group
+49-170-9165551 | @hlgr360 | http://work.haufegroup.io

Haufe-Lexware GmbH & Co.KG
Munzinger Str. 9, 79111 Freiburg
http://www.haufe-lexware.com<http://www.haufe-lexware.com/>

On Jul 6, 2017, at 12:01 PM, Evgeny Prigorodov <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems to be the only existing PAS plugin that can integrate a Zope instance with AD FS (dm.zope.saml2 only works in a Plone site). It has weight 9 on PyPI.

**Comment by hlgr360** [comment]
I just want to make sure that we have actively monitored and maintained repo in our public Github. It is part of good housekeeping.
I am also pointing to our Open Source policy for reference: https://github.com/Haufe-Lexware/open-source/blob/master/open-source.md

If this repo is in compliance with our policy, feel free to close this issue as resolved.

:-)
Holger
______________________________________________________
Holger Reinhardt
CTO – Haufe.Group
+49-170-9165551 | @hlgr360 | http://work.haufegroup.io

Haufe-Lexware GmbH & Co.KG
Munzinger Str. 9, 79111 Freiburg
http://www.haufe-lexware.com<http://www.haufe-lexware.com/>

On Jul 7, 2017, at 11:30 AM, saromba <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Holger,



we (the LexBIZ Team) are responsible for that repo.

What is the current task ? Evgeny only commented something...



Regards,

Sascha Rombach




Gesendet: Freitag, 07. Juli 2017 um 11:05 Uhr
Von: "Holger Reinhardt" <notifications@github.com<mailto:notifications@github.com>>
An: "Haufe-Lexware/hl.pas.samlplugin" <hl.pas.samlplugin@noreply.github.com<mailto:hl.pas.samlplugin@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Betreff: Re: [Haufe-Lexware/hl.pas.samlplugin] Can this repo be removed? (#3)

Is anyone taking care of it and feeling responsible?
______________________________________________________
Holger Reinhardt
CTO – Haufe.Group
+49-170-9165551 | @hlgr360 | http://work.haufegroup.io

Haufe-Lexware GmbH & Co.KG
Munzinger Str. 9, 79111 Freiburg
http://www.haufe-lexware.com<http://www.haufe-lexware.com/>

On Jul 6, 2017, at 12:01 PM, Evgeny Prigorodov <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


It seems to be the only existing PAS plugin that can integrate a Zope instance with AD FS (dm.zope.saml2 only works in a Plone site). It has weight 9 on PyPI.
